# -*- coding: utf-8 -*-
"""stress_detection_prova.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNmOoFcgw80kB7oz0npNeoLqnq7B6QsG

# 😤 Stress Detection su Video
Basato su [Geek-ubaid/Stress-Detection](https://github.com/Geek-ubaid/Stress-Detection)

Questo notebook:
1. Installa le dipendenze
2. Carica un video da Google Drive o upload diretto
3. Analizza il livello di stress frame per frame (sopracciglia + emozioni via FER)
4. Genera un video annotato + CSV + grafico

## 1. Installazione dipendenze
"""

# Installa le librerie necessarie
#!pip install -q dlib opencv-python-headless fer matplotlib pandas
#!apt-get -qq install -y cmake libopenblas-dev liblapack-dev libx11-dev

# Scarica il modello dlib per i 68 landmark facciali
import os
if not os.path.exists('shape_predictor_68_face_landmarks.dat'):
 #   !wget -q http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
 #   !bzip2 -d shape_predictor_68_face_landmarks.dat.bz2
    print(' Modello scaricato!')
else:
    print(' Modello già presente.')

"""## 2. Carica il video
Scegli uno dei due metodi: upload diretto oppure Google Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

VIDEO_PATH = '/content/drive/MyDrive/Lie_detector/Dataset/BagOfLies/Finalised/User_0/run_0/video.mp4'  # <-- modifica questo path

"""## 3. Configurazione parametri"""

# ---- PARAMETRI ----
SAMPLE_EVERY_N_FRAMES = 3    # Analizza 1 frame ogni N (velocità vs dettaglio)
USE_FER = True               # Usa anche FER per la classificazione emozioni
SAVE_ANNOTATED_VIDEO = True  # Salva video con stress overlay
OUTPUT_CSV = 'stress_results.csv'
OUTPUT_VIDEO = 'stress_output.mp4'
# -------------------

print('Configurazione OK ')

"""## 4. Funzioni di analisi"""

import cv2
import dlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, HTML

if USE_FER:
    from fer.fer import FER # Changed import statement
    fer_detector = FER(mtcnn=True)

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

def get_brow_stress(landmarks):
    """Calcola stress da distanza inter-sopracciglio (logica Geek-ubaid)"""
    left_brow  = [(landmarks.part(i).x, landmarks.part(i).y) for i in range(17, 22)]
    right_brow = [(landmarks.part(i).x, landmarks.part(i).y) for i in range(22, 27)]
    dist = right_brow[0][0] - left_brow[-1][0]
    stress = min(100, max(1, int(np.exp(-dist / 50) * 100)))
    return stress

def get_fer_stress(frame):
    """Stima stress da emozioni: anger + fear + disgust come proxy"""
    try:
        result = fer_detector.detect_emotions(frame)
        if result:
            emotions = result[0]['emotions']
            # Emozioni associate allo stress come proxy
            stress_proxy = emotions.get('angry', 0) + emotions.get('fear', 0) + emotions.get('disgust', 0)
            return round(stress_proxy * 100, 1), emotions
    except:
        pass
    return None, None

def stress_color(level):
    """Verde → giallo → rosso in base al livello"""
    if level < 33:
        return (0, 200, 0)
    elif level < 66:
        return (0, 165, 255)
    else:
        return (0, 0, 220)

print('Funzioni caricate ')

"""## 5. Analisi del video"""

cap = cv2.VideoCapture(VIDEO_PATH)
fps = cap.get(cv2.CAP_PROP_FPS)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

print(f'Video: {w}x{h} @ {fps:.1f} fps — {total_frames} frame totali (~{total_frames/fps:.1f}s)')

if SAVE_ANNOTATED_VIDEO:
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(OUTPUT_VIDEO, fourcc, fps, (w, h))

records = []
frame_idx = 0
processed = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    if frame_idx % SAMPLE_EVERY_N_FRAMES == 0:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = detector(gray)
        timestamp = frame_idx / fps

        brow_stress = None
        fer_stress = None
        emotions_dict = None

        for face in faces:
            landmarks = predictor(gray, face)
            brow_stress = get_brow_stress(landmarks)

            # Disegna bounding box
            x1, y1 = face.left(), face.top()
            x2, y2 = face.right(), face.bottom()
            cv2.rectangle(frame, (x1, y1), (x2, y2), (200, 200, 200), 1)

        if USE_FER and brow_stress is not None:
            fer_stress, emotions_dict = get_fer_stress(frame)

        # Stress finale: media pesata brow + fer (se disponibile)
        if brow_stress is not None and fer_stress is not None:
            final_stress = int(0.5 * brow_stress + 0.5 * fer_stress)
        elif brow_stress is not None:
            final_stress = brow_stress
        else:
            final_stress = None

        records.append({
            'frame': frame_idx,
            'time_s': round(timestamp, 2),
            'brow_stress': brow_stress,
            'fer_stress': fer_stress,
            'final_stress': final_stress,
            'face_detected': len(faces) > 0
        })

        # Overlay testo sul frame
        if final_stress is not None:
            color = stress_color(final_stress)
            cv2.putText(frame, f'Stress: {final_stress}%', (20, 45),
                        cv2.FONT_HERSHEY_DUPLEX, 1.2, color, 2)
            cv2.putText(frame, f't={timestamp:.1f}s', (20, 80),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200, 200, 200), 1)
            # Barra stress
            bar_len = int(final_stress * 2)
            cv2.rectangle(frame, (20, 95), (220, 110), (50, 50, 50), -1)
            cv2.rectangle(frame, (20, 95), (20 + bar_len, 110), color, -1)

        processed += 1

    if SAVE_ANNOTATED_VIDEO:
        out.write(frame)

    frame_idx += 1
    if frame_idx % 100 == 0:
        pct = frame_idx / total_frames * 100
        print(f'  Progresso: {pct:.1f}% ({frame_idx}/{total_frames})', end='\r')

cap.release()
if SAVE_ANNOTATED_VIDEO:
    out.release()

df = pd.DataFrame(records)
df.to_csv(OUTPUT_CSV, index=False)
print(f'\n\n Analisi completata! Frame processati: {processed}')
print(f'CSV salvato: {OUTPUT_CSV}')
if SAVE_ANNOTATED_VIDEO:
    print(f'Video salvato: {OUTPUT_VIDEO}')

"""## 6. Risultati e grafici"""

# Statistiche riepilogative
df_valid = df[df['face_detected'] == True]

print('=== STATISTICHE STRESS ===')
print(f'Frame con volto rilevato : {len(df_valid)} / {len(df)}')
print(f'Stress medio (brow)      : {df_valid["brow_stress"].mean():.1f}')
if USE_FER:
    print(f'Stress medio (FER proxy) : {df_valid["fer_stress"].mean():.1f}')
print(f'Stress medio (finale)    : {df_valid["final_stress"].mean():.1f}')
print(f'Stress massimo           : {df_valid["final_stress"].max()}')
print(f'Stress minimo            : {df_valid["final_stress"].min()}')

# Grafico andamento stress nel tempo
fig, axes = plt.subplots(2, 1, figsize=(14, 8))

# Plot principale
ax = axes[0]
ax.plot(df_valid['time_s'], df_valid['brow_stress'], label='Sopracciglia', alpha=0.5, linewidth=1, color='steelblue')
if USE_FER:
    ax.plot(df_valid['time_s'], df_valid['fer_stress'], label='FER proxy', alpha=0.5, linewidth=1, color='orange')
ax.plot(df_valid['time_s'], df_valid['final_stress'], label='Stress finale', linewidth=2.5, color='crimson')

# Soglie
ax.axhline(33, color='green', linestyle='--', linewidth=0.8, alpha=0.6, label='Soglia bassa (33)')
ax.axhline(66, color='red', linestyle='--', linewidth=0.8, alpha=0.6, label='Soglia alta (66)')
ax.fill_between(df_valid['time_s'], 66, 100, alpha=0.05, color='red')
ax.fill_between(df_valid['time_s'], 0, 33, alpha=0.05, color='green')

ax.set_xlabel('Tempo (s)')
ax.set_ylabel('Livello di stress (0-100)')
ax.set_title('Andamento Stress nel Tempo')
ax.legend(loc='upper right')
ax.set_ylim(0, 105)
ax.grid(True, alpha=0.3)

# Istogramma distribuzione
ax2 = axes[1]
ax2.hist(df_valid['final_stress'].dropna(), bins=20, color='crimson', alpha=0.7, edgecolor='white')
ax2.axvline(df_valid['final_stress'].mean(), color='black', linestyle='--', linewidth=1.5, label=f'Media: {df_valid["final_stress"].mean():.1f}')
ax2.set_xlabel('Livello di stress')
ax2.set_ylabel('Frequenza (frame)')
ax2.set_title('Distribuzione Livelli di Stress')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('stress_plot.png', dpi=150, bbox_inches='tight')
plt.show()
print('Grafico salvato: stress_plot.png')

"""## 7. Download risultati"""

from google.colab import files

# Scarica CSV
files.download(OUTPUT_CSV)

# Scarica grafico
files.download('stress_plot.png')

# Scarica video annotato (può essere pesante, decommenta se necessario)
# files.download(OUTPUT_VIDEO)